Use GNU format tarballs to support longer paths
This fixes errors related to paths being too long, which is common when
using git dependencies. Note that cargo itself switched from UStar to
GNU format in 2020.

    thread 'main' panicked at src/main.rs:290:32:
        called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "provided value is too long when setting path for some-crate-0.123.123/src/" }